name: Run Laravel Pint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, pdo_mysql

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Run Laravel Pint (auto-fix)
        run: ./vendor/bin/pint

      - name: Commit and push if needed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || (git commit -m "automatically formatted code" && git push)
